---
output: word_document
params:
  cdm: cdm
  fl_counts: fl_counts
  rp_counts: rp_counts
  rec_counts: rec_counts
  set_title: set_title
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
title <- params$set_title
```

---
title: "`r title`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fluroquinolones
```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(CDMConnector)
library(DrugExposureDiagnostics)
library(PatientProfiles)
library(CodelistGenerator)
library(dplyr)
library(tidyr)
library(gt)
library(ggplot2)
```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
gt(fl_counts %>% 
  filter(strata_name == "Overall") %>% 
  select(group, group_name,  group_level, variable_name, estimate) %>% 
  pivot_wider(names_from = variable_name, values_from = estimate) %>% 
  arrange(group,group_name))


fl_counts %>% 
  filter(!is.na(estimate),
         group_name == "Codelist",
         strata_name == "Year",
         variable_name == "Person count") %>% 
  mutate(strata_level = as.numeric(strata_level)) %>% 
  ggplot() + 
  geom_col(aes(x = strata_level, y = estimate)) + 
  facet_wrap(vars(group), scales = "free_y", ncol = 1) +
  theme_minimal() +
  ylab("Person count") +
  xlab("Year")
```



## Rectal prolapse
```{r, warning=FALSE, message=FALSE, echo=FALSE}
gt(rp_counts %>% 
  filter(strata_name == "Overall") %>% 
  select(group, group_name,  group_level, variable_name, estimate) %>% 
  pivot_wider(names_from = variable_name, values_from = estimate) %>% 
  arrange(group,group_name))


rp_counts %>% 
  filter(!is.na(estimate),
         group_name == "Codelist",
         strata_name == "Year",
         variable_name == "Person count") %>% 
  mutate(strata_level = as.numeric(strata_level)) %>% 
  ggplot() + 
  geom_col(aes(x = strata_level, y = estimate)) + 
  facet_wrap(vars(group), scales = "free_y", ncol = 1) +
  theme_minimal() +
  ylab("Person count") +
  xlab("Year")
```


## Rectopexy
```{r, warning=FALSE, message=FALSE, echo=FALSE}
gt(rec_counts %>% 
  filter(strata_name == "Overall") %>% 
  select(group, group_name,  group_level, variable_name, estimate) %>% 
  pivot_wider(names_from = variable_name, values_from = estimate) %>% 
  arrange(group,group_name))

rec_counts %>% 
  filter(!is.na(estimate),
         group_name == "Codelist",
         strata_name == "Year",
         variable_name == "Person count") %>% 
  mutate(strata_level = as.numeric(strata_level)) %>% 
  ggplot() + 
  geom_col(aes(x = strata_level, y = estimate)) + 
  facet_wrap(vars(group), scales = "free_y", ncol = 1) +
  theme_minimal() +
  ylab("Person count") +
  xlab("Year")
```
